

FROM node:18-alpine AS builder

WORKDIR /app


COPY package*.json ./


RUN npm ci


COPY . .

ENV VITE_API_URL=https://cardapio-backend-prod-791776403069.us-central1.run.app/api


RUN npm run build


FROM nginx:alpine


COPY --from=builder /app/dist /usr/share/nginx/html


COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80


HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget --quiet --tries=1 --spider http://localhost:80/ || exit 1

CMD ["nginx", "-g", "daemon off;"]