FROM node:22-alpine

WORKDIR /app

# Copiar package.json primeiro para aproveitar cache
COPY package*.json ./

# Remover qualquer lock file e node_modules existente
RUN rm -rf node_modules package-lock.json || true

RUN npm install -D @testing-library/user-event

# Instalar dependências
RUN npm install

# Copiar código fonte
COPY . .

EXPOSE 3000

# Comando de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]