services:
  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      backend:
        condition: service_started
    networks:
      - cardapio-network
    restart: unless-stopped

  # Backend Node.js
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=cardapio_user
      - DB_PASSWORD=cardapio_pass
      - DB_NAME=cardapio_db
      - JWT_SECRET=dev-jwt-secret-123
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cardapio-network
    restart: unless-stopped

  # Banco MySQL - CONFIGURAÇÃO MELHORADA
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cardapio_db
      MYSQL_USER: cardapio_user
      MYSQL_PASSWORD: cardapio_pass
      # Configurações adicionais para evitar problemas
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - cardapio-network
    restart: unless-stopped
    # Healthcheck melhorado
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 30s
    # Comando para configurações adicionais
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=128M
      - --max-connections=200

  # Interface do Banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 50M
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cardapio-network
    restart: unless-stopped

  # Cache Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cardapio-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  cardapio-network:
    driver: bridge