FROM node:18-alpine

WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependências
RUN npm install
RUN npm install -g nodemon

RUN npm install --save-dev @babel/core @babel/preset-env @babel/plugin-transform-runtime babel-jest
RUN npm install --save @babel/runtime

# Copiar código fonte
COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]
